### ISSUE TITLE
How to use GetText from gettext-lib?

### ISSUE THREAD

**Issue by akarienta** [laget-se/react-gettext-parser#13]
I am trying to use gettext with React. You have [this line](https://github.com/laget-se/react-gettext-parser/blob/73b8dda03fa2bdab21aa0888191447f2f5bdf3d8/tests/fixtures/Es6Strings.js#L2) in your tests, which library is that? It seems nothing like `gettext-lib` exists in npm repo.

**Comment by alexanderwallin** [comment]
`gettext-lib` is a totally fictitious library. The JavaScript files in the fixtures folder are not actually exectued, only parsed.
