### ISSUE TITLE
Adding babel plugin support

### ISSUE THREAD

**Issue by OmgImAlexis** [laget-se/react-gettext-parser#17]
I'd like to use this with vuejs as they have a babel plugin that can convert the `.vue` file into jsx format so this should work after it's gone through that plugin.

Is it possible to pass in a list of plugins to use before get text?

Ref: https://github.com/vuejs/babel-plugin-transform-vue-jsx

**Comment by alexanderwallin** [comment]
So you're writing JSX and use that as source, and then that plugin transforms that into regular Vue function calls in transpile time?

**Comment by alexanderwallin** [comment]
Is this still on your wishlist, @OmgImAlexis?

**Comment by OmgImAlexis** [comment]
Yes, sorry for the late reply the notification was buried.

**Comment by alexanderwallin** [comment]
Have you tried [`babel-plugin-react-gettext-parser`](https://github.com/alexanderwallin/babel-plugin-react-gettext-parser)?

**Comment by alexanderwallin** [comment]
@OmgImAlexis I'm gonna close this, but feel free to reopen it if needed.
