### ISSUE TITLE
Poedit error: Duplicate message definition

### ISSUE THREAD

**Issue by tonila** [laget-se/react-gettext-parser#19]
.pot file is filled with duplicate message definitions, when same translation string is used across files.

e.g.
```
#: src/components/AppBar.js:91
msgid "Production tests"
msgstr ""

#: src/components/ProductionTest.js:23
msgid "Production tests"
msgstr ""
```

**Comment by alexanderwallin** [comment]
Hi @tonila. Thanks for reporting the issue. Could you provide us with `AppBar.js` and `ProductionTest.js` so that we can reproduce it?

**Comment by tonila** [comment]
Hi, i'll try to provide reproducable test case.

ti 20. kesäkuuta 2017 klo 12.00 Alexander Wallin <notifications@github.com>
kirjoitti:

**Comment by tonila** [comment]
Hi,

I created a simples possible reproducable test case:

[xgetext-test.zip](https://github.com/laget-se/react-gettext-parser/files/1087913/xgetext-test.zip)

**Comment by alexanderwallin** [comment]
Turned out the gulp plugin didn't merge identical messages. Should be fixed now!

Could you publish this, @EmilScherdin?

**Comment by EmilScherdin** [comment]
@alexanderwallin Merge https://github.com/laget-se/react-gettext-parser/pull/18?

**Comment by alexanderwallin** [comment]
@EmilScherdin This one, #19

**Comment by EmilScherdin** [comment]
@alexanderwallin Oh, missed that!
