### ISSUE TITLE
Provide an option to trim strings of whitespace

### ISSUE THREAD

**Issue by alexanderwallin** [laget-se/react-gettext-parser#22]
For instance, when using [lioness](https://github.com/alexanderwallin/lioness) and Prettier, any text wrapped in `<T>` will be put on a new line and indented accordingly:

```js
const MyComp = () =>
  <div>
    <T>
      This is a text
    </T>
  </div>
```

This will result in translatable string with lots of whitespace in them:

```pot
msgid ""
"\n"
"      This is a text"
```

A `trim` options, or a set of `trim*` options, would come in handy here.

**Comment by alexanderwallin** [comment]
@EmilScherdin Would you minor bump this and publish, please?

**Comment by EmilScherdin** [comment]
@alexanderwallin Done! ✅
