### ISSUE TITLE
What is the expected format of `config.js`

### ISSUE THREAD

**Issue by phtrivier** [laget-se/react-gettext-parser#23]
The CLI seems to accept a js file as a `--config` option.
What is the expected format ? I tried variations of this, in order to make things work for lioness (https://github.com/alexanderwallin/lioness#via-babel-plugin-react-gettext-parser): 

```
var opts = {
  funcArgumentsMap: {
    tc: ['msgid', null],
    tcn: ['msgid', 'msgid_plural', null, null],
    tcp: ['msgctxt', 'msgid', null],
    tcnp: ['msgctxt', 'msgid', 'msgid_plural', null, null],
    t: ['msgid'],
    tn: ['msgid', 'msgid_plural', null],
    tp: ['msgctxt', 'msgid'],
    tnp: ['msgctxt', 'msgid', 'msgid_plural', null],
  },
  componentPropsMap: {
    T: {
      message: 'msgid',
      messagePlural: 'msgid_plural',
      context: 'msgctxt',
      comment: 'comment',
    },
  },
};

module.exports = opts;
// Not sure if this is supposed to work:
//    export default opts
// or even:
//    return ops
```

However my pot files do not get generated as I hope, and I'm unsure if this is my CLI or in the configuration...

**Comment by alexanderwallin** [comment]
That config looks good to me. How are you invoking `react-gettext-parser`?

**Comment by phtrivier** [comment]
Okay, that seems to be working know, I suppose I had another error somewhere. Thanks !
