### ISSUE TITLE
Add support for gettext comments

### ISSUE THREAD

**Issue by SeanHayes** [laget-se/react-gettext-parser#26]
Is there a way to do this?

**Comment by alexanderwallin** [comment]
Currently there isn't, although it would sure be nice to have. Something like:

```js
// Translators: This is used in the dropdown menu
gettext('Show')
```

or

```js
gettext('Show', { comment: 'This is used in the dropdown menu' })
```

**Comment by SeanHayes** [comment]
I was thinking, it would be awesome if there's a "do it all" function that can accept optional ES6 keyword args.

**Comment by alexanderwallin** [comment]
You mean passing a single object to a function?

```js
translate({
  msgid: 'Show',
  comment: 'This is used in the dropdown menu',
})
```

**Comment by SeanHayes** [comment]
Yeah.

**Comment by alexanderwallin** [comment]
@SeanHayes Check out v1.5.0 if you want!
