### ISSUE TITLE
Support child strings wrapped in curly braces

### ISSUE THREAD

**Issue by ramiel** [laget-se/react-gettext-parser#27]
Sometimes I want to write the message as text child in a component, i.e.

```js
<GetText>translate me</GetText>
```

and this works if in the options I set
```
{
  ...,
  GetText: {
      children: 'msgid',
      messagePlural: 'msgid_plural',
      context: 'msgctxt',
      comment: 'comment',
  },
}
```

but the extraction fails is I write

```js
<GetText>{'a static string to translate'}</GetText>
```

I do like this to write `{'a string with a {placeholder}'}`.

How can I do?

**Comment by alexanderwallin** [comment]
For regular strings, this should work even without the `children: 'msgid'` config. My guess is that other types of strings are simply not supported a.t.m., the culprit being this line: https://github.com/laget-se/react-gettext-parser/blob/master/src/parse.js#L187

Let's leave this issue here as a feature request.

**Comment by ramiel** [comment]
ok, thank you

**Comment by alexanderwallin** [comment]
Do you have an example of what you need to accomplish? Maybe we can solve it with the existing features.

**Comment by ramiel** [comment]
Yes, as I said I'd wish to be able to pass a string as child in my gettext component

```
<MyGetText placeholder="value">{'a string with a  {placeholder}'}</MyGetText>
```
This is because I need to interpolate value at runtime later. I have to specify that I'm using a custom component for translations, it was used by our basecode before and we do not want ot use already existing translation components.

**Comment by alexanderwallin** [comment]
Oh btw, if you want to submit a PR for this, @ramiel, you are of course welcome to do so! Can't really promise when there will be time to implement this.

**Comment by alexanderwallin** [comment]
@ramiel Check out v1.5.0 if you feel like it!

**Comment by ramiel** [comment]
Great, thank you and sorry for my silence, I've been busy
