### ISSUE TITLE
Script react-gettext-parser not available via yarn

### ISSUE THREAD

**Issue by michel404** [laget-se/react-gettext-parser#29]
This is an issue that occurs when using react-gettext-parser in combination with yarn.

#### Steps to reproduce
- run `yarn init`
- run `yarn add react-gettext-parser`
- add the following line to `package.json`: `  "scripts": { "react-gettext-parser": "react-gettext-parser" },`
- run `yarn react-gettext-parser`

#### Actual result
The console outputs this error:
```
yarn run v1.3.2
$ react-gettext-parser
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
#### Expected result
A successful run of react-gettext-parser:
```
yarn run v1.3.2
$ react-gettext-parser
msgid ""
msgstr ""
"Content-Type: text/plain; charset=utf-8\n"
"POT-Creation-Date: Mon Apr 09 2018 14:30:09 GMT+0200 (CEST)\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
Did write .pot contents to undefined
Done in 0.25s.
```
#### Work around / suggested solution
The executable file `node_modules/.bin/react-gettext-parser` uses line endings that causes yarn to error. Changing these CRLF line terminators to just LF line terminators fixes this issue.

#### Versions
Ubuntu 16.04 LTS
react-gettext-parser 1.4.1
yarn 1.3.2

**Comment by alexanderwallin** [comment]
Hey @michel404! Thanks for the (well-formatted) report. The line endings in the source code are LF:

![image](https://user-images.githubusercontent.com/6952455/38511946-0a473448-3c2a-11e8-8cc5-6c39ada0e4f8.png)

so I think this might be something `yarn` is doing. Perhaps you could have a look [over there](https://github.com/yarnpkg/yarn/issues?utf8=✓&q=is%3Aissue+is%3Aopen+crlf) to see if you can find a solution?

**Comment by tdaved** [comment]
Hey @michel404, I also had this issue, seems to be npm changes line endings nowadays. I ended up a solution described [here](https://github.com/nodejs/node/issues/11478). An overall solution is described [here too](https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo). Hope this helps.

**Comment by michel404** [comment]
Hi @tdaved, yep that works. I regard that as a workaround, not a solution because I have to apply it every time I run `yarn` (i.e. for every clean build)...

@alexabderwallin, thanks for checking the line endings. I'm not fully convinced however, since git by default also does some magic regarding line endings at fetch or checkout or something (so Windows and Linux users can actually work together).

Thanks also for the pointer to yarn, maybe I can find an solution for this issue there...

**Comment by alexanderwallin** [comment]
This all sounds like it would have major implications all over the place. I don't have any ideas on what to change in this library in order to fix this, so I any of you do, please let me know!

**Comment by alexanderwallin** [comment]
@ridderholt Would you mind publishing a new version with the https://github.com/laget-se/react-gettext-parser/commit/8185475e7aa9acedcd519624dfb13e47bfd1f92f fix? Somewhat shooting in the dark, but it was the only thing I could think of.

**Comment by visuallization** [comment]
I found a work-around I can work with. 
I use the API and create a file called "buildPot.js" with the following content:

```
const textParser = require('react-gettext-parser');
const config = require('../config/gettext.config');

// Parse a file and put it into a pot file
textParser.parseGlob(['src/**/{*.js,*.jsx}'], config, () => {
  console.log("Done");
});
```

Then I create a new script in my package.json:

```
"scripts": {
    "build:pot": "node scripts/buildPot.js"
  },
```

Now when I call yarn build:pot in my terminal (mac osx), the file gets generated.

cheers

**Comment by ridderholt** [comment]
@alexanderwallin Version 1.4.2 is up on NPM now

**Comment by alexanderwallin** [comment]
@ridderholt Thank you!

@michel404 @visuallization @tdaved I just tried with the new version, and it is working here. Could you guys double-check?

**Comment by alexanderwallin** [comment]
I'll close this, but feel free to reopen if anyone's having problems.
