### ISSUE TITLE
not working on mac osx: env: node\r: No such file or directory

### ISSUE THREAD

**Issue by visuallization** [laget-se/react-gettext-parser#31]
Ahoi, 

Thank you for your work on this tool!
Currently I have a problem getting it to run on mac osx. 
In Terminal running `yarn react-gettext-parser` it throws the error:

```
env: node\r: No such file or directory
error An unexpected error occurred: "Command failed.
Exit code: 127
Command: sh
```

When changing the line endings in bin/react-gettext-parser.js from CRLF to LF it works just fine.

Could you fix this so I can just update the package?

Kind Regards,
Florentin

**Comment by alexanderwallin** [comment]
Howdeh! 

Thanks for the report, @visuallization. This issue is already being tracked in https://github.com/laget-se/react-gettext-parser/issues/29. If you have any ideas on what to do, it would be very welcome.
