### ISSUE TITLE
Options for comments and headers configuration

### ISSUE THREAD

**Issue by sHooKDT** [laget-se/react-gettext-parser#40]
I think there should be a way to disable these location comments or 'POT-Creation-Date' in generated .pot files.

**Comment by alexanderwallin** [comment]
How so?

**Comment by sHooKDT** [comment]
@alexanderwallin maybe add some options to these functions https://github.com/laget-se/react-gettext-parser/blob/master/src/json2pot.js#L44

**Comment by alexanderwallin** [comment]
I'm curious as to why you want to configure the comments?

**Comment by sHooKDT** [comment]
They're absolute and thus different for all developers. This leads to git conflicts and also reveals my personal dir structure, which is not the thing I want in company's code of course.
The same thing with some headers. POT-Creation-Date is different every time, so we can't merge translations automatically.

**Comment by sHooKDT** [comment]
In our company we use `sed` to strip some headers, comments, unused translations to keep PO files clean. So, I think it would be nice to have a way to configure it and stop suffer :)

**Comment by alexanderwallin** [comment]
Yes, paths should definitely be relative the project root. I have not experienced absolute paths before. Are you running `react-gettext-parser` from outside the project directory? Would it make sense to have an option to set the project root? I'm not too keen on adding options on excluding things that are in the gettext spec.

I understand the header merge issue is annoying. How about an callback option of this shape?

```
transformHeaders: headers => transformedHeaders
```

Then you could essentially do what you want with them.

**Comment by alexanderwallin** [comment]
Hey @sHooKDT, have a look at #41 and see if it floats your boat!

**Comment by sHooKDT** [comment]
Hi. Sorry that I had no time to contribute and even continue a conversation last 2 weeks :)

I think your idea about transforming headers is just brilliant. It is much more flexible and simple than approach I have imagined (like adding flags to disable each header).
And thanks for spending time on the PR, it do the thing.

But don't you think this option should be spread for also parseFile and parseGlob functions? Now it is also acceptable, but if one wants to use it, he should manually call extract, then toPot and then write it to a file. So maybe we should just pass this configuration through calls.

*What about paths comments:*
I have used a Node API in my extracting script (in a separate package) and then ran it from node_modules. So it produced an absolute paths.

> Would it make sense to have an option to set the project root?
Yes, I think it will. It will make comment at least usable.

But anyway, I would be happy to have a way to remove these location comment as they are not really needed. gettext spec doesn't say that location is necessary. It depends on extraction tool. For example xgettext doesn't add them.

**Comment by sHooKDT** [comment]
Also about comments. Looks like there is a way to strip comments easily when using extract -> toPot -> write combination. I can just manually map through extracted messages and remove reference property. Maybe it will do what I need.
So if it really works (will try later) and you think it is not really common case, then the problem looks solved for me.

**Comment by alexanderwallin** [comment]
> But don't you think this option should be spread for also parseFile and parseGlob functions?

Absolutely, the PR has been updated!

**Comment by alexanderwallin** [comment]
I've opened a separate issue for the paths problem.
