### ISSUE TITLE
Ensure source code references are relative

### ISSUE THREAD

**Issue by alexanderwallin** [laget-se/react-gettext-parser#42]
As described in #40, source code references can sometimes be absolute, which of course is wrong.

> I have used a Node API in my extracting script (in a separate package) and then ran it from node_modules. So it produced an absolute paths.

**Comment by alexanderwallin** [comment]
Hey @sHooKDT, you can try this one out and see if it solves your problem!

**Comment by sHooKDT** [comment]
Hi, @alexanderwallin 
This works, path are now relative on my setup.
Great work!

**Comment by sHooKDT** [comment]
Also, we can add an option to specify root directory.
For example inside `src` dir.
Just an idea. Not the case for me now.

**Comment by alexanderwallin** [comment]
Good news!

We could indeed, but let's wait for an actual need for it to come up. :)
