### ISSUE TITLE
Cannot install with npm

### ISSUE THREAD

**Issue by ezelohar** [laget-se/react-gettext-parser#47]
Hi team, -

It seems that the new version cannot be installed with NPM anymore. 

My NPM version is 6.4.1
My Node version is 11.1.0

Here is the video showing the issue
https://www.useloom.com/share/bd6623d9deae407885eadd4361424ba1

Running command
npm install react-gettext-parser

Will return

> websupercell:tw ezelohar$ npm install react-gettext-parser
npm ERR! path /Users/ezelohar/Downloads/tw/node_modules/react-gettext-parser/lib/bin.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/ezelohar/Downloads/tw/node_modules/react-gettext-parser/lib/bin.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ezelohar/.npm/_logs/2019-01-08T14_50_58_860Z-debug.log

**Comment by KornelSzaltanowicz** [comment]
+1 same for me

**Comment by KornelSzaltanowicz** [comment]
Any updates?

**Comment by alexanderwallin** [comment]
Fix on the way!

**Comment by sHooKDT** [comment]
Hope this will be fixed soon.
The needed files are not packaged. Looks like failed publish.
Just for interest, how did it happen?

![image](https://user-images.githubusercontent.com/5585758/51024598-d2b24480-15ab-11e9-92fc-03a0a6f7ea6b.png)

**Comment by alexanderwallin** [comment]
I've just published 1.8.1. Give it a go!

The issue was simply that it was published without being properly built and bundled.
