### ISSUE TITLE
react-gettext-parser config file

### ISSUE THREAD

**Issue by pronebird** [laget-se/react-gettext-parser#51]
The config file is being mentioned in many places but there is absolutely zero information regarding how that file should look like.

**Comment by alexanderwallin** [comment]
The config file should export a JSON object containing keys matching the listed options. I'll have a go at making this more clear.

I'd appreciate it if you would drop the snarky tone. Doing this on my free time, you know.

**Comment by pronebird** [comment]
Thanks man!

**Comment by pedrosimao** [comment]
Hello, have you already done an example of config file?
I am also struggling with that.

**Comment by alexanderwallin** [comment]
I added a section about it here: https://github.com/laget-se/react-gettext-parser/blob/master/README.md#configuration-file

Please reopen the issue if you think it could be clarified better!
