### ISSUE TITLE
React-gettext-parser glob is broken?

### ISSUE THREAD

**Issue by pronebird** [laget-se/react-gettext-parser#52]
Just tried to extract the translations today. It does not work on my TS codebase.

```
react-gettext-parser --output locales/messages.pot src/**/*.{ts, tsx}
```

It picks up a few translations from `src/{folder name}/*.ts` but does not go any further down the file tree. How do you even use it?

**Comment by alexanderwallin** [comment]
First, you can try to put the glob inside quotation marks.

Second, are you using the default gettext functions (`gettext`, `dgettext` etc.) or custom ones? If you use custom ones, you need to [provide a config file](https://github.com/laget-se/react-gettext-parser/issues/51#issuecomment-466445204) that defines your [`funcArgumentsMap`](https://github.com/laget-se/react-gettext-parser#funcargumentsmap).

If neither of these work, please provide a reproducible case, like a GitHub repo.

**Comment by pronebird** [comment]
Closing because I've moved on with the other solution that uses TypeScript which matches my tech stack and is probably more favorable in terms of the amount of extra dependencies.

For the record, I use `gettext` and `pgettext` functions, which must be standard.
