### ISSUE TITLE
Parsing fails with Flow annotations

### ISSUE THREAD

**Issue by sHooKDT** [laget-se/react-gettext-parser#53]
Seems like there is a problems with parsing Flow annotated files with current version on babylon. A bit later I can provide an example.

It fails to parse something like:
```
export default connect<_, _, _, _, _>({})(Component);
```

The problem came up after annotating some react files in project.
We faced compilation fails and then just upgraded our babel toolchain to 7+ so the problem was solved. But react-gettext-parser is unable to parse files anyway.

I think we need to update version of parser here too.

**Comment by sHooKDT** [comment]
I've created a PR to solve the issue.

**Comment by alexanderwallin** [comment]
PR is merged and v1.9.0 is out!
