### ISSUE TITLE
use decorator error when calls reactGettextParser.extractMessagesFromGlob

### ISSUE THREAD

**Issue by TerenYeung** [laget-se/react-gettext-parser#55]
when I use decorator in .tsx and run webpack build, it emits error like this: UnhandledPromiseRejectionWarning: SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (6:0);

I find it typo when the source code uses decoratorsLegacy in lib/defaults.js but decorators or decorators-legacy；

see detail at: https://babeljs.io/docs/en/babel-parser;

**Comment by alexanderwallin** [comment]
Thanks, @TerenYeung. I've just pushed a fix in v1.9.1. Let me know you're still having issues.
