### ISSUE TITLE
No wrap msgid when writing the string in .pot file

### ISSUE THREAD

**Issue by rstefan1** [laget-se/react-gettext-parser#64]

**Comment by alexanderwallin** [comment]
I would need some more details on this.

**Comment by rstefan1** [comment]
When `msgid`s are very long, the parser wraps them to multiple lines. 

E.g.: When the string is `very-long.......very-long`, the msgid  written in .pot file is:
```
msgid ""
"very-long...."
"....very-long"
```

It is nice to have an option like `nowrap` when writing strings in .pot files.

**Comment by alexanderwallin** [comment]
Right! We use [`gettext-parser`](https://github.com/smhg/gettext-parser) to create the .pot files, so it would have to be raised there.
