### ISSUE TITLE
Sanity check?!! Can't get files parsed

### ISSUE THREAD

**Issue by tdotholla** [laget-se/react-gettext-parser#66]
Greetings! 
i've been trying desparately to get this to work all day to no avail. Just reaching out for a little help here. 

My functions look like this: (i'm using `react-intl` formatting functions, which wrap `Intl` functions)

```
// located in /packages/suite/src/client/common/components/someFile.tsx`
formatMessage("common.ok")
```

Trying to utilize react-gettext-parser via npm script: 
```

"build:pot": "react-gettext-parser --config ./packages/suite/src/i18n/react-gettext-parser.config.js --output messages.pot  'packages/suite/src/client/common/components/**/*.{js, jsx, tsx, ts}'",
```

my config file: 
```
// /packages/suite/src/i18n/react-gettext-parser.config.js
module.exports = {
    funcArgumentsMap: {
        formatMessage: ["msgid"],
    },
    trim: true,
};
```

when i run `yarn build:pot`
my console output is:  
```
Did write .pot contents to messages.pot
Done in 0.49s.
```

and of course my `messages.pot` file looking like this: 

```
// /messages.pot
msgid ""
msgstr ""
"Content-Type: text/plain; charset=utf-8\n"
"POT-Creation-Date: Fri Dec 06 2019 17:03:21 GMT-0500 (Eastern Standard "
"Time)\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
```

Can anyone see why this isn't pulling the content from my `formatMessage` functions?

Thanks!!

**Comment by alexanderwallin** [comment]
Greetings! Could you set up a simple repo reproducing this?
