### ISSUE TITLE
Merge pot files?

### ISSUE THREAD

**Issue by honi** [laget-se/react-gettext-parser#74]
What's the recommended approach to merge the generated pot files with an existing po file that might already have some translations? It would be awesome if this tool already included this since it seems it's something you'll always need right?

**Comment by alexanderwallin** [comment]
There's a package called [pot-merge](https://github.com/laget-se/pot-merge) that'll do this for you:

```
import { mergePotContents } from 'pot-merge';

await mergePotContents(oldPot, newPot)
```

If you want more sugar you can check out [narp](https://github.com/laget-se/narp) which has `push` and `pull` commands that handles merged pots and syncs with Transifex or POEditor.
