### ISSUE TITLE
Possibility to disable headers

### ISSUE THREAD

**Issue by reginaochotzki** [laget-se/react-gettext-parser#79]
I could really use the feature that you can disable the header. The header doesn't give us any added value and always leads to merge conflicts, so Gitlab can't merge automatically, it has to be merged manually. Would it be possible to include a command line option so that no header is output with it?

**Comment by alexanderwallin** [comment]
Is it the `pot-creation-date` header that gives you conflicts?

**Comment by reginaochotzki** [comment]
Yes

**Comment by alexanderwallin** [comment]
That's a little peculiar. So it's able to auto merge other changes but not the date header?

**Comment by reginaochotzki** [comment]
No, not really. My workaround now is to always revert the line before check in.

**Comment by alexanderwallin** [comment]
But I'm curious why a changing date string causes merge conflicts when changed translation strings do not. 🤔

**Comment by reginaochotzki** [comment]
Because the translations are almost always in different lines.

**Comment by alexanderwallin** [comment]
Right! We'll set something up, let me think for a bit and I'll get back to you.

**Comment by reginaochotzki** [comment]
thanks :-)

**Comment by alexanderwallin** [comment]
I'm leaning towards `--header` option that you can use to set a header to whatever you want. That'll be a broadly usable feature and not so edge casey. Providing an empty value would remove it.

```
react-gettext-parser --config myconfig.js --header pot-creation-date= --output results.pot 'src/**/*.js'
```

What do you think about that?

**Comment by reginaochotzki** [comment]
Ah cool, that sound great :-)

**Comment by alexanderwallin** [comment]
Sorry about the delay, but there's a 1.16.10 version out now that has the `--header` option. You can read about it in the README!

**Comment by alexanderwallin** [comment]
This is poorly documented, but if the configuration file takes a `transformHeaders` option and will be passed on to `toPot()`, meaning you can manipulate the headers all you want there.

**Comment by reginaochotzki** [comment]
Thank you!

**Comment by reginaochotzki** [comment]
Hi, unfortunately this does not seem to work.
my command line arguments are

  '--header',
  'pot-creation-date=',
  '--output',
  'locale/de/LC_MESSAGES/djangojs.pot',
  'frontend/javascript/src/**/*.{js,jsx}'

and in output file still following line changed 
"POT-Creation-Date: Tue Feb 09 2021 08:01:38 GMT+0100 (Central European Standard Time)\n"

I would expect the line to be changed into something like 
"POT-Creation-Date:"

**Comment by reginaochotzki** [comment]
I then looked into the code and saw that in the file json2pot.js in line 38 the current date is still written in. Where is the command line argument used at all?

**Comment by alexanderwallin** [comment]
The `--header` argument is CLI only. It parses the headers you provide and then [does a headers transformation](https://github.com/laget-se/react-gettext-parser/blob/master/src/cli.js#L67-L70) via the `transformHeaders` option.

It's not super obvious, but if you check `--help` you'll see that you need to append a `--` after you enter your headers. If it's still not working, try wrapping your header assignment inside double quotes.

Here's how I would write your command in the terminal:

```
react-gettext-parser --header "pot-creation-date=" -- --output locale/de/LC_MESSAGES/djangojs.pot "frontend/javascript/src/**/*.{js,jsx}"
```

**Comment by reginaochotzki** [comment]
Sorry, but still does not work for me
in command line I ran
yarn run -- react-gettext-parser --header "pot-creation-date=" -- --output locale/de/LC_MESSAGES/django2js.pot "frontend/javascript/src/**/*.{js,jsx}"
 and following exception
 /Users/rochotzki/Cloud/OnlineAcademy/academy-web/Sources/Web/node_modules/babylon/lib/index.js:4457
  throw err;
  ^

SyntaxError: Unexpected token, expected ; (1:6)
    at Parser.pp$5.raise (/Users/rochotzki/Cloud/OnlineAcademy/academy-web/Sources/Web/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/rochotzki/Cloud/OnlineAcademy/academy-web/Sources/Web/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.semicolon (/Users/rochotzki/Cloud/OnlineAcademy/academy-web/Sources/Web/node_modules/babylon/lib/index.js:1742:38)
    at Parser.pp$1.parseExpressionStatement (/Users/rochotzki/Cloud/OnlineAcademy/academy-web/Sources/Web/node_modules/babylon/lib/index.js:2236:8)
    at Parser.parseExpressionStatement (/Users/rochotzki/Cloud/OnlineAcademy/academy-web/Sources/Web/node_modules/babylon/lib/index.js:5934:20)
    at Parser.pp$1.parseStatement (/Users/rochotzki/Cloud/OnlineAcademy/academy-web/Sources/Web/node_modules/babylon/lib/index.js:1911:17)
    at Parser.parseStatement (/Users/rochotzki/Cloud/OnlineAcademy/academy-web/Sources/Web/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/Users/rochotzki/Cloud/OnlineAcademy/academy-web/Sources/Web/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/rochotzki/Cloud/OnlineAcademy/academy-web/Sources/Web/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/rochotzki/Cloud/OnlineAcademy/academy-web/Sources/Web/node_modules/babylon/lib/index.js:1673:17) {
  pos: 6,
  loc: Position { line: 1, column: 6 }
}
error Command failed with exit code 1.


same with 
yarn run -- react-gettext-parser --header "pot-creation-date=''" -- --output locale/de/LC_MESSAGES/django2js.pot "frontend/javascript/src/**/*.{js,jsx}"

Exception does not occur on using this line
yarn react-gettext-parser --header "pot-creation-date=''" -- --output locale/de/LC_MESSAGES/django2js.pot "frontend/javascript/src/**/*.{js,jsx}"

but it does not then remove the date, so i think it is not executed correctly

**Comment by alexanderwallin** [comment]
Oh sorry, i mistyped, you use a colon!

```
--header "pot-creation-date:"
```
