### ISSUE TITLE
travis is not activated ?

### ISSUE THREAD

**Issue by jmfrancois** [laget-se/react-gettext-parser#8]
Hi,

Why travis ci is not activated on this project ?
I would like to use it on my current project and I just can't add module not under a CI.

I only it under a different path https://travis-ci.org/alexanderwallin/react-gettext-parser
which do not exists anymore on github.

It seems @alexanderwallin you have moved the repository from your github account to laget-se organisation.

AFAIK you should create it again on travis and add the badge to the readme.

Please add QA back to this project.

**Comment by alexanderwallin** [comment]
Hi @jmfrancois!

> I would like to use it on my current project and I just can't add module not under a CI.

How do you mean, what is it that you can't add?

> It seems @alexanderwallin you have moved the repository from your github account to laget-se organisation.

Yes, the repo was transferred to @lagetse, and AFAIK they don't have Travis set up.

> Please add QA back to this project.

What QA are you referring to?

**Comment by jmfrancois** [comment]
By QA I'm referring  to "Quality Assurance" so "tests + CI + test coverage"

I mean If react-gettext-parser is not under continuous integration so I have no Quality Assurance it works well.

By "I can't add" I mean I can't use it. My policy to select a tool is

* it should work
* it must have tests
* it must be on a CI (travis is free for OSS project)

I have report this as an issue because there are tests, so why not put it back to travis ?

What do you mean by "they don't have Travis set up" ?
AFAIK you just have to be part of the organisation to setup travis for a given repository.
Who could do that ? @lagetse ?

**Comment by alexanderwallin** [comment]
I am not part of their organization anymore, so it's not available form my Travis account. I'll see if we can get it up and running!

**Comment by alexanderwallin** [comment]
It would be nice having Travis set up. Do you have an account set up at @lagetse?

@EmilScherdin @kentos @MickeLarsson @ridderholt

**Comment by EmilScherdin** [comment]
@alexanderwallin @jmfrancois This is added now.
