### ISSUE TITLE
ES6 Template Literals

### ISSUE THREAD

**Issue by Bojch** [laget-se/react-gettext-parser#9]
Hi, i have problem with ES6 Template Literals they are not parsed and an empty msgid is in POT file and this is everywhere with back-ticks
```
_T(`Log in to your account`)
```
What can be done?

**Comment by alexanderwallin** [comment]
Hey @Bojch. This is definitely feature that should be supported. I'll implement it as soon as I can.

**Comment by Bojch** [comment]
Hey @alexanderwallin great to hear that, thnx for response and great job.
